---
openstack_repository_prefix: "https://github.com/openstack-ansible/"

openstack_controller_ip: "{{ hostvars[groups.controller[0]].ansible_default_ipv4.address }}"

openstack_rabbitmq_host: "{{ openstack_controller_ip }}"
openstack_mysql_host: "{{ openstack_controller_ip }}"

openstack_identity_endpoint_host: "{{ openstack_controller_ip }}"
openstack_image_endpoint_host: "{{ openstack_controller_ip }}"
openstack_compute_endpoint_host: "{{ openstack_controller_ip }}"
openstack_network_endpoint_host: "{{ openstack_controller_ip }}"

harness_http_proxy_environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"

harness_no_http_proxy_environment:
    http_proxy: ''
    HTTP_PROXY: ''
    https_proxy: ''
    HTTPS_PROXY: ''

harness_docker_binary_images:

    - name: ubuntu
      file: ubuntu-14_04.tar.xz
      group: all

    - name: debian
      file: debian-wheezy.tar.xz
      group: compute

harness_docker_build_images:

  - name: sequenceiq/pam
    tag: ubuntu-14.04
    repo: "https://github.com/sequenceiq/docker-pam.git"
    version: HEAD 
    dir: sequenceiq_docker-pam 
    buildsub: ubuntu-14.04
    group: controller

  - name: harnesscloud/iaas-deployment-docker-image
    tag: latest
    repo: "https://github.com/harnesscloud/iaas-deployment-docker-image.git"
    version: HEAD
    dir: harnesscloud_iaas-deployment-docker-image 
    buildsub: ''
    group: controller

  - name: harnesscloud/debian-cloudimage
    tag: latest
    repo: "https://github.com/harnesscloud/docker-debian-cloudimage.git"
    version: fix-grid5k
    dir: harnesscloud_docker-debian-cloudimage 
    buildsub: ''
    group: compute

  - name: harnesscloud/conpaas-director
    tag: latest
    repo: "https://github.com/harnesscloud/docker-conpaas-director.git"
    version: fix-grid5k
    dir: harnesscloud_docker-conpaas-director 
    buildsub: ''
    group: compute

  - name: phusion/baseimage
    tag: latest
    repo: "https://github.com/phusion/baseimage-docker.git"
    version: HEAD
    dir: phusion_baseimage-docker
    buildsub: image
    group: compute

  - name: harnesscloud/baseimage-cloud
    tag: latest
    repo: "https://github.com/harnesscloud/docker-baseimage-cloud.git"
    version: HEAD
    dir: harnesscloud_docker-baseimage-cloud 
    buildsub: ''
    group: compute

  - name: harnesscloud/conpaas-worker
    tag: latest
    repo: "https://github.com/harnesscloud/docker-conpaas-worker.git"
    version: fix-grid5k
    dir: harnesscloud_docker-conpaas-worker
    buildsub: ''
    group: compute


