---
openstack_repository_prefix: "https://github.com/openstack-ansible/"

openstack_controller_ip: "{{ hostvars[groups.controller[0]].ansible_default_ipv4.address }}"

openstack_rabbitmq_host: "{{ openstack_controller_ip }}"
openstack_mysql_host: "{{ openstack_controller_ip }}"

openstack_identity_endpoint_host: "{{ openstack_controller_ip }}"
openstack_image_endpoint_host: "{{ openstack_controller_ip }}"
openstack_compute_endpoint_host: "{{ openstack_controller_ip }}"
openstack_network_endpoint_host: "{{ openstack_controller_ip }}"

harness_http_proxy_environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"


harness_no_http_proxy_environment:
    http_proxy: ''
    HTTP_PROXY: ''
    https_proxy: ''
    HTTPS_PROXY: ''


harness_docker_build_images:

  - name: harnesscloud/iaas-deployment-docker-image
    tag: latest
    repo: "https://github.com/harnesscloud/iaas-deployment-docker-image.git"
    version: HEAD
    dir: harnesscloud_iaas-deployment-docker-image 
    buildsub: ''
    group: controller

  - name: harnesscloud/conpaas-director
    tag: latest
    repo: "https://github.com/harnesscloud/docker-conpaas-director.git"
    version: HEAD
    dir: harnesscloud_docker-conpaas-director 
    buildsub: ''
    group: compute

  - name: xtreemfs/xtreemfs-harness-common
    tag: latest
    repo: "https://github.com/harnesscloud/xtreemfs-docker.git"
    version: HEAD
    dir: harnesscloud_xtreemfs-docker
    buildsub: xtreemfs-harness-common
    group: controller

  - name: xtreemfs/xtreemfs-harness-manager
    tag: latest
    repo: "https://github.com/harnesscloud/xtreemfs-docker.git"
    version: HEAD
    dir: harnesscloud_xtreemfs-docker
    buildsub: xtreemfs-harness-manager
    group: controller

  - name: xtreemfs/xtreemfs-harness-osd
    tag: latest
    repo: "https://github.com/harnesscloud/xtreemfs-docker.git"
    version: HEAD
    dir: harnesscloud_xtreemfs-docker
    buildsub: xtreemfs-harness-osd
    group: controller

  #- name: xtreemfs/xtreemfs-client
  #  tag: latest
  #  repo: "https://github.com/harnesscloud/xtreemfs-client-docker.git"
  #  version: HEAD
  #  dir: harnesscloud_xtreemfs-client-docker
  #  buildsub: ''
  #  group: controller

harness_docker_pull_images:

  - name: harnesscloud/conpaas-worker
    tag: latest
    group: compute

  - name: harnesscloud/baseimage-cloud
    tag: latest
    group: compute
