---
openstack_identity_endpoint_host: "10.1.0.2"

openstack_identity_admin_url: >
  http://{{ openstack_identity_endpoint_host }}:35357/v2.0
openstack_identity_internal_url: >
  http://{{ openstack_identity_endpoint_host }}:5000/v2.0
openstack_identity_public_url: >
  http://{{ openstack_identity_endpoint_host }}:5000/v2.0

openstack_image_endpoint_host: "10.1.0.2"
openstack_compute_endpoint_host: "10.1.0.2"
openstack_network_endpoint_host: "10.1.0.2"

