---
openstack_run_dir: "{{ lookup('env', 'PWD') }}"
openstack_identity_admin_token: >
  {{ lookup('password', openstack_run_dir +
                        '/private/credentials/keystone-admin-token
                         length=20
                         chars=ascii_letters,digits') }}

mariadb_bind_address: "0.0.0.0"

