---
neutron_network_external_name: "public",
neutron_network_external_device: "eth1",
neutron_network_external_ip: "10.1.0.2",
neutron_network_external_netmask: "16",
neutron_network_external_allocation_pool_start: "10.1.0.100",
neutron_network_external_allocation_pool_end: "10.1.0.200",
neutron_network_external_dns_servers: "8.8.8.8"
