---
- hosts: controller
  sudo: True
  roles:
    - chrony
    - mariadb
    - rabbitmq-server
    - keystone
    - glance
    - nova-controller
    - neutron-controller
    - neutron-network

- hosts: compute-001
  sudo: True
  roles:
    - chrony
    - nova-compute

