---
- hosts: localhost
  gather_facts: False
  sudo: False
  tasks:
    
    - name: check out required roles
      delegate_to: localhost
      connection: local
      git:
        repo: "{{ openstack_repository_prefix }}ansible-role-{{ item }}.git"
        dest: roles/{{ item }}
        update: yes
      with_items:
        - chrony
        - docker
        - mysql
        - rabbitmq-server
        - keystone
        - glance
        - nova-controller
        - nova-compute-docker
        - cinder-controller
        - cinder-volume
        - horizon

    - name: check out experimental required roles to enable lbaas
      delegate_to: localhost
      connection: local
      git:
        repo: "https://github.com/gioannidis/ansible-role-{{ item }}.git"
        dest: roles/{{ item }}
        update: yes
      with_items:
        - neutron-controller
        - neutron-network

    - name: check out library needed for demo deployment from github.com
      git:
        repo:
          '{{ openstack_repository_prefix }}openstack-ansible-modules.git'
        dest: library/openstack-ansible-modules
        update: yes

    - name: clone docker image repositories to local system
      git:
        repo: "{{ item.repo }}"
        version: "{{ item.version }}"
        dest: harness/{{ item.dir }}
        update: no
      with_items: harness_docker_build_images
