---
- hosts: all
  sudo: True
  roles:
    - upgrade
    - chrony
    - docker

- hosts: controller
  sudo: True
  tasks:

    - name: ensure required packages for prep are installed
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - python-mysqldb
        - python-keystoneclient

- hosts: all:!network
  sudo: True
  tasks:

    # FIXME: obv
    - name: add route to 10.2.0.0/16 network...
      command: route add -net 10.2.0.0/16 gw 10.1.0.3
 
