---
- hosts: all
  sudo: True
  roles:
    - upgrade
    - chrony
    - docker

- hosts: controller
  sudo: True
  tasks:

    - name: ensure required packages for prep are installed
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - python-mysqldb
        - python-keystoneclient
