- hosts: controller
  sudo: True
  tasks:

    - name: ensure required packages for prep are installed
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - iptables-persistent

    - name: enable net.ipv4.ip_forward in sysctl
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present

    - name: check to see if masquerade rule is present
      command: iptables -t nat -C POSTROUTING -s 10.1.0.0/16 -o eth0 -j MASQUERADE
      register: ipt_masquerade
      ignore_errors: yes
      changed_when: false

    - name: add masquerade rule if not present
      shell: >
        iptables -t nat -A POSTROUTING -s 10.1.0.0/16 -o eth0 -j MASQUERADE &&
        invoke-rc.d iptables-persistent save
      when: ipt_masquerade|failed
