---
- hosts: controller
  sudo: True
  roles:
    - mariadb
    - rabbitmq-server
    - keystone
    - glance
    - nova-controller
    - neutron-controller

- hosts: network
  sudo: True
  roles:
    - neutron-network

- hosts: compute
  sudo: True
  roles:
    - nova-compute
