---
- hosts: all
  sudo: True
  roles:
    - chrony

- hosts: controller
  sudo: True
  roles:
    - mysql
    - rabbitmq-server
    - keystone
    - glance
    - nova-controller
    - neutron-controller
    - horizon

- hosts: network
  sudo: True
  roles:
    - neutron-network

- hosts: controller:compute
  sudo: True
  roles:
    - docker

- hosts: controller:compute
  sudo: True
  tasks:

    - name: ensure that docker is configured to use http_proxy
      lineinfile:
        dest: /etc/default/docker
        line: export http_proxy="{{ lookup('ENV', 'http_proxy') }}"
        regexp: export http_proxy=
        state: present
      register: docker_http_proxy

    - name: ensure that docker is configured to use http_proxy
      lineinfile:
        dest: /etc/default/docker
        line: export HTTP_PROXY="{{ lookup('ENV', 'http_proxy') }}"
        regexp: export HTTP_PROXY=
        insertafter: export http_proxy=
        state: present
      register: docker_big_http_proxy

    - name: restart docker if necessary
      service:
        name: docker
        state: restarted
      when: docker_http_proxy|changed or docker_big_http_proxy|changed

    - name: ensure that login user is in the docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
        state: present

    - name: ensure that pip is installed
      shell: curl -s https://bootstrap.pypa.io/get-pip.py | python -
             creates=/usr/local/bin/pip

    - name: ensure docker client libraries are installed
      pip:
        name: docker-py
        state: latest

- hosts: compute
  sudo: True
  roles:
    - nova-compute-docker
