---
- hosts: all
  sudo: True
  tasks:
    - name: disable grid5000 http_proxy by default
      lineinfile:
        dest: /etc/environment
        regexp: '^http_proxy="http://proxy:3128"'
        state: absent

- hosts: all
  sudo: True
  roles:
    - chrony

- hosts: controller
  sudo: True
  roles:
    - mysql
    - rabbitmq-server
    - keystone
    - glance
    - nova-controller
    - neutron-controller
    - horizon

- hosts: network
  sudo: True
  roles:
    - neutron-network

- hosts: compute
  sudo: True
  roles:
    - nova-compute
