---
- hosts: all
  sudo: True
  roles:
    - chrony

- hosts: controller
  sudo: True
  roles:
    - mysql
    - rabbitmq-server
    - keystone
    - glance
    - nova-controller
    - neutron-controller
    - horizon

- hosts: network
  sudo: True
  roles:
    - neutron-network

- hosts: compute
  sudo: True
  roles:
    - docker

- hosts: compute
  sudo: True
  tasks:
    - name: ensure that login user is in the docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
        state: present

    - name: ensure that pip is installed
      shell: curl -s https://bootstrap.pypa.io/get-pip.py | python -
             creates=/usr/local/bin/pip

    - name: ensure docker client libraries are installed
      pip:
        name: docker-py
        state: latest

- hosts: compute
  sudo: True
  roles:
    - nova-compute-docker
