---
- hosts: all
  sudo: True
  tasks:
    - name: remove grid5000 repository
      lineinfile:
        dest: /etc/apt/sources.list
        regexp: '^deb http://apt.nancy.grid5000.fr/debian sid main'
        state: absent

- hosts: all
  sudo: True
  roles:
    - chrony

- hosts: controller
  sudo: True
  roles:
    - mysql
    - rabbitmq-server
    - keystone
    - glance
    - nova-controller
    - neutron-controller
    - horizon

- hosts: network
  sudo: True
  roles:
    - neutron-network

- hosts: compute
  sudo: True
  roles:
    - nova-compute
