---
- hosts: all
  sudo: True
  roles:
    - chrony

- hosts: controller:compute
  sudo: True
  roles:
    - docker

- hosts: controller
  sudo: True
  roles:
    - mysql
    - rabbitmq-server
    - keystone
    - glance
    - nova-controller
    - neutron-controller
    - horizon

- hosts: network
  sudo: True
  roles:
    - neutron-network

- hosts: compute
  sudo: True
  roles:
    - nova-compute-docker

- hosts: controller:compute
  sudo: True
  tasks:

    - name: ensure that docker is configured to use http_proxy
      lineinfile:
        dest: /etc/default/docker
        line: export http_proxy="{{ lookup('env', 'http_proxy') }}"
        regexp: export http_proxy=
        state: present
      register: docker_http_proxy

    - name: ensure that docker is configured to use http_proxy
      lineinfile:
        dest: /etc/default/docker
        line: export HTTP_PROXY="{{ lookup('env', 'http_proxy') }}"
        regexp: export HTTP_PROXY=
        insertafter: export http_proxy=
        state: present
      register: docker_big_http_proxy

    - name: restart docker if necessary
      service:
        name: docker
        state: restarted
      when: docker_http_proxy|changed or docker_big_http_proxy|changed

    - name: ensure that login user is in the docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
        state: present

    - name: ensure that pip is installed
      shell: curl -s https://bootstrap.pypa.io/get-pip.py | python -
             creates=/usr/local/bin/pip

    - name: ensure docker client libraries are installed
      pip:
        name: docker-py
        state: latest

    - name: ensure docker image build directories exist
      file:
        path: "{{ item }}"
        owner: "{{ ansible_ssh_user }}"
        state: directory
      with_items:
        - "{{ ansible_env.PWD }}/.ansible_cache"
        - "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild"

    - name: copy binary images to remote system
      copy:
        src: docker/{{ item }}
        dest: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/"
        owner: "{{ ansible_ssh_user }}"
      with_items:
        - debian-wheezy.tar.xz
        - ubuntu-14_04.tar.xz

    - name: register list of docker images
      environment:
        http_proxy: ''
      command: docker images
      register: docker_image_check
      changed_when: false

    - name: load debian image if necessary
      environment:
        http_proxy: ''
      shell: xzcat {{ ansible_env.PWD }}/.ansible_cache/dockerbuild/debian-wheezy.tar.xz | docker load
      when: -1 == docker_image_check.stdout.find("debian")

    - name: load ubuntu image if necessary
      environment:
        http_proxy: ''
      shell: xzcat {{ ansible_env.PWD }}/.ansible_cache/dockerbuild/ubuntu-14_04.tar.xz | docker load
      when: -1 == docker_image_check.stdout.find("ubuntu")

    - name: clone docker image repositories to remote systems
      sudo_user: "{{ ansible_ssh_user }}"
      git:
        repo: "{{ item.url }}"
        dest: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/{{ item.dir }}"
        update: no
      with_items:
        - { url: "https://github.com/phusion/baseimage-docker.git", dir: phusion_baseimage-docker }
        - { url: "https://github.com/harnesscloud/docker-baseimage-cloud.git", dir: harnesscloud_docker-baseimage-cloud }
        - { url: "https://github.com/sequenceiq/docker-pam.git", dir: sequenceiq_docker-pam }
        - { url: "https://github.com/harnesscloud/iaas-deployment-docker-image.git", dir: harnesscloud_iaas-deployment-docker-image }
        - { url: "https://github.com/harnesscloud/docker-debian-cloudimage.git", dir: harnesscloud_docker-debian-cloudimage }
        - { url: "https://github.com/harnesscloud/docker-conpaas-director.git", dir: harnesscloud_docker-conpaas-director }
        - { url: "https://github.com/harnesscloud/docker-conpaas-worker.git", dir: harnesscloud_docker-conpaas-worker }

    - name: ensure that docker image builds are configured to use https_proxy
      lineinfile:
        dest: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/{{ item }}/Dockerfile"
        line: ENV https_proxy={{ lookup('env', 'https_proxy') }}
        insertafter: ^MAINTAINER
        state: present
      with_items:
        - phusion_baseimage-docker/image
        - harnesscloud_docker-baseimage-cloud
        - sequenceiq_docker-pam/ubuntu-14.04
        - harnesscloud_iaas-deployment-docker-image
        - harnesscloud_docker-debian-cloudimage 
        - harnesscloud_docker-conpaas-director
        - harnesscloud_docker-conpaas-worker

    - name: ensure that docker image builds are configured to use http_proxy
      lineinfile:
        dest: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/{{ item }}/Dockerfile"
        line: ENV http_proxy={{ lookup('env', 'http_proxy') }}
        insertafter: ^MAINTAINER
        state: present
      with_items:
        - phusion_baseimage-docker/image
        - harnesscloud_docker-baseimage-cloud
        - sequenceiq_docker-pam/ubuntu-14.04
        - harnesscloud_iaas-deployment-docker-image
        - harnesscloud_docker-debian-cloudimage 
        - harnesscloud_docker-conpaas-director
        - harnesscloud_docker-conpaas-worker

    - name: ensure that docker images are configured to NOT use http_proxy at runtime...
      lineinfile:
        dest: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/{{ item }}/Dockerfile"
        line: ENV http_proxy=''
        insertbefore: ^CMD
        state: present
      with_items:
        - phusion_baseimage-docker/image
        - harnesscloud_docker-baseimage-cloud
        - sequenceiq_docker-pam/ubuntu-14.04
        - sequenceiq_docker-pam/ubuntu-14.04
        - harnesscloud_iaas-deployment-docker-image
        - harnesscloud_docker-debian-cloudimage 
        - harnesscloud_docker-conpaas-director
        - harnesscloud_docker-conpaas-worker

    - name: ensure that docker images are configured to NOT use https_proxy at runtime...
      lineinfile:
        dest: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/{{ item }}/Dockerfile"
        line: ENV https_proxy=''
        insertbefore: ^CMD
        state: present
      with_items:
        - phusion_baseimage-docker/image
        - harnesscloud_docker-baseimage-cloud
        - sequenceiq_docker-pam/ubuntu-14.04
        - harnesscloud_iaas-deployment-docker-image
        - harnesscloud_docker-debian-cloudimage 
        - harnesscloud_docker-conpaas-director
        - harnesscloud_docker-conpaas-worker

    - name: ensure docker images have been built
      environment:
        http_proxy: ''
      docker_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag }}"
        path: "{{ ansible_env.PWD }}/.ansible_cache/dockerbuild/{{ item.dir }}"
        state: present
      with_items:
        - { name: phusion/baseimage, tag: latest, dir: phusion_baseimage-docker/image }
        - { name: harnesscloud/baseimage-cloud, tag: latest, dir: harnesscloud_docker-baseimage-cloud }
        - { name: sequenceiq/pam, tag: ubuntu-14.04, dir: sequenceiq_docker-pam/ubuntu-14.04 }
        - { name: harnesscloud/iaas-deployment-docker-image, tag: latest, dir: harnesscloud_iaas-deployment-docker-image }
        - { name: harnesscloud/debian-cloudimage, tag: latest, dir: harnesscloud_docker-debian-cloudimage }
        - { name: harnesscloud/conpaas-director, tag: latest, dir: harnesscloud_docker-conpaas-director }
        - { name: harnesscloud/conpaas-worker, tag: latest, dir: harnesscloud_docker-conpaas-worker }

- hosts: controller
  sudo: True
  tasks:

    - name: update admin.openrc from template
      template:
        src: templates/admin.openrc
        dest: "{{ ansible_env.PWD }}/admin.openrc"
        owner: "{{ ansible_ssh_user }}"
        mode: 0600

    - name: create harness tenant
      environment:
        http_proxy: ''
      keystone_user:
        endpoint: "{{ openstack_identity_admin_url }}"
        token: "{{ openstack_identity_admin_token }}"
        tenant: harness
        tenant_description: "Harness Tenant"

    - name: create harness user
      environment:
        http_proxy: ''
      keystone_user:
        endpoint: "{{ openstack_identity_admin_url }}"
        token: "{{ openstack_identity_admin_token }}"
        tenant: harness
        user: harness
        password: "{{ openstack_identity_harness_password }}"

    - name: associate _member_ role with harness user
      environment:
        http_proxy: ''
      keystone_user:
        endpoint: "{{ openstack_identity_admin_url }}"
        token: "{{ openstack_identity_admin_token }}"
        tenant: harness
        user: harness
        role: _member_

    - name: update harness.openrc template
      template:
        src: templates/harness.openrc
        dest: "{{ ansible_env.PWD }}/harness.openrc"
        owner: "{{ ansible_ssh_user }}"
        mode: 0600

    - name: check to see what images have been registered with glance
      environment:
        http_proxy: ''
      command: glance --os-auth-url "{{ openstack_identity_public_url }}" --os-tenant-name harness --os-username harness --os-password "{{ openstack_identity_harness_password }}" image-list
      register: glance_image_check
      changed_when: false

    - name: import harnesscloud/conpaas-director image into glance if necessary
      environment:
        http_proxy: ''
      shell: docker save {{ item }} | glance --os-auth-url "{{ openstack_identity_public_url }}" --os-tenant-name harness --os-username harness --os-password "{{ openstack_identity_harness_password }}" image-create --name={{ item }} --is-public=true --container-format=docker --disk-format=raw
      when: -1 == glance_image_check.stdout.find("{{ item }}")
      with_items:
        - harnesscloud/baseimage-cloud
        - harnesscloud/conpaas-director
        - harnesscloud/conpaas-worker

    - name: query glance for harnesscloud/conpaas-director image id
      environment:
        http_proxy: ''
      glance_image:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        name: harnesscloud/conpaas-director
        file: /tmp/dummy
        state: present
      register: conpaas_director_image
 
    - name: query glance for harnesscloud/conpaas-worker image id
      environment:
        http_proxy: ''
      glance_image:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        name: harnesscloud/conpaas-worker
        file: /tmp/dummy
        state: present
      register: conpaas_worker_image
    
    # Ansible neutron modules lists all tenants to get ids, but this is not
    # permitted for non-admin users. Need to fix neutron_* modules as non-admin
    # *should* be able to create networks, associate floating ips, etc.

    - name: ensure harness user has admin role
      environment:
        http_proxy: ''
      keystone_user:
        endpoint: "{{ openstack_identity_admin_url }}"
        token: "{{ openstack_identity_admin_token }}"
        tenant: harness
        user: harness
        role: admin

    - name: ensure internal network is registered
      environment:
        http_proxy: ''
      neutron_network:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        tenant_name: harness
        name: harness-net
        state: present
      register: openstack_network_internal

    - name: ensure subnet internal network is registered
      environment:
        http_proxy: ''
      neutron_subnet:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        tenant_name: harness
        name: harness-subnet
        network_name: harness-net
        cidr: 192.168.13.0/24
        enable_dhcp: true
        gateway_ip: 192.168.13.1
        dns_nameservers: 8.8.8.8
        state: present

    - name: ensure router exists
      environment:
        http_proxy: ''
      neutron_router:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        tenant_name: harness
        name: harness-router
        state: present

    - name: ensure router has interface connected to internal network
      environment:
        http_proxy: ''
      neutron_router_interface:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        tenant_name: harness
        router_name: harness-router
        subnet_name: harness-subnet
        state: present

    - name: ensure router has external network gateway
      environment:
        http_proxy: ''
      neutron_router_gateway:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        router_name: harness-router
        network_name: public
        state: present

    - name: create ssh keypair
      command: ssh-keygen -q -f {{ ansible_env.PWD }}/.ssh/id_rsa -P ""
               creates={{ ansible_env.PWD }}/.ssh/id_rsa

    - name: capture public key in variable
      command: cat {{ ansible_env.PWD }}/.ssh/id_rsa.pub
      register: pubkey
      changed_when: false

    - name: add ssh keypair to nova
      environment:
        http_proxy: ''
      nova_keypair:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        name: harness-keypair
        public_key: "{{ pubkey.stdout }}"
        state: present

    # the neutron_sec_group module needs work...
    
    - name: verify existence of harness security group
      environment:
        http_proxy: ''
      command: neutron --os-auth-url "{{ openstack_identity_public_url }}" --os-tenant-name harness --os-username harness --os-password "{{ openstack_identity_harness_password }}" security-group-show harness-secgroup
      register: verify_secgroup
      ignore_errors: yes
      changed_when: false
    
    - name: create harness-secgroup security group if necessary
      environment:
        http_proxy: ''
      command: neutron --os-auth-url "{{ openstack_identity_public_url }}" --os-tenant-name harness --os-username harness --os-password "{{ openstack_identity_harness_password }}" security-group-create harness-secgroup
      when: verify_secgroup|failed
   
    - name: ensure that harness-secgroup allows ping
      environment:
        http_proxy: ''
      command: neutron --os-auth-url "{{ openstack_identity_public_url }}" --os-tenant-name harness --os-username harness --os-password "{{ openstack_identity_harness_password }}" security-group-rule-create --direction=ingress --protocol=icmp harness-secgroup
      when: verify_secgroup|failed

    - name: ensure that harness-secgroup allows ssh
      environment:
        http_proxy: ''
      command: neutron --os-auth-url "{{ openstack_identity_public_url }}" --os-tenant-name harness --os-username harness --os-password "{{ openstack_identity_harness_password }}" security-group-rule-create --direction=ingress --protocol=tcp --port-range-min=22 --port-range-max=22 harness-secgroup
      when: verify_secgroup|failed

    - name: ensure that harness-secgroup allows http
      environment:
        http_proxy: ''
      command: neutron --os-auth-url "{{ openstack_identity_public_url }}" --os-tenant-name harness --os-username harness --os-password "{{ openstack_identity_harness_password }}" security-group-rule-create --direction=ingress --protocol=tcp --port-range-min=80 --port-range-max=80 harness-secgroup
      when: verify_secgroup|failed

    - name: ensure that harness-secgroup allows https
      environment:
        http_proxy: ''
      command: neutron --os-auth-url "{{ openstack_identity_public_url }}" --os-tenant-name harness --os-username harness --os-password "{{ openstack_identity_harness_password }}" security-group-rule-create --direction=ingress --protocol=tcp --port-range-min=443 --port-range-max=443 harness-secgroup
      when: verify_secgroup|failed

    - name: ensure harness iaas configuration directory exists
      file:
        path: /etc/harness-iaas
        owner: root
        group: root
        mode: 0700
        state: directory

    - name: update harness-iaas configuration files from templates
      template:
        src: templates/etc/harness-iaas/{{ item }}
        dest: /etc/harness-iaas/{{ item }}
        owner: root
        group: root
        mode: 0600
      with_items:
        - compute_list
        - crs.constraints

    - name: ensure that harness iaas service is started
      docker:
        name: harness-iaas-services
        image: harnesscloud/iaas-deployment-docker-image
        env:
          PASSWORD: "{{ openstack_identity_harness_password }}"
          NOVA_ENDPOINT: "{{ openstack_compute_endpoint_host }}:5000"
          IRM_INTERFACE: "{{ openstack_network_external_device }}"
          DEFAULT_IMAGE: "{{ conpaas_worker_image.id }}"
        volumes: /etc/harness-iaas:/etc/harness-iaas:ro
        ports:
          - 8888:8888
          - 56789:56789

    - name: create a new conpaas-admin virtual machine instance
      nova_compute:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        name: conpaas-director
        flavor_id: 1
        image_id: "{{ conpaas_director_image.id }}"
        nics:
          - net-id: "{{ openstack_network_internal.id }}"
        key_name: harness-keypair
        security_groups: harness-secgroup
        wait: "yes"
        state: present
        user_data: |
          export USERNAME=test
          export PASSWORD=password
          export CRS_URL=http://{{ ansible_default_ipv4.address }}:56789
          export IMAGE_ID=conpaas-worker

    - name: ensure floating ip is associated with vm instance
      neutron_floating_ip:
        auth_url: "{{ openstack_identity_public_url }}"
        login_tenant_name: harness
        login_username: harness
        login_password: "{{ openstack_identity_harness_password }}"
        instance_name: conpaas-director
        network_name: public
        state: present
      register: harness_floating_ip

    - name: ping harness virtual machine
      command: ping -c 4 {{ harness_floating_ip.public_ip }}
      changed_when: false

    #- name: wait for ssh to become available
    #  wait_for:
    #    host: "{{ harness_floating_ip.public_ip }}"
    #    port: 22

    #- name: verify that virtual machine can be logged into via ssh
    #  command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cirros@{{ harness_floating_ip.public_ip }} hostname
    #  changed_when: false
 
    #- name: check to see if dnat rule is present
    #  command: iptables -t nat -C PREROUTING -p tcp --dport 443 -j DNAT --to {{ harness_floating_ip.public_ip }}
    #  register: ipt_dnat
    #  ignore_errors: yes
    #  changed_when: false

    #- name: add masquerade rule if not present
    #  command: iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to {{ harness_floating_ip.public_ip }}
    #  when: ipt_dnat|failed

