- hosts: network
  sudo: True
  tasks:

    - name: enable net.ipv4.ip_forward in sysctl
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present

    - name: check to see if masquerade rule is present
      command: iptables -t nat -C POSTROUTING -s {{ openstack_network_external_network }} -o {{ opentstack_network_external_device }} -j MASQUERADE
      register: ipt_masquerade
      ignore_errors: yes
      changed_when: false

    - name: add masquerade rule if not present
      command: iptables -t nat -A POSTROUTING -s {{ openstack_network_external_network }} -o {{ opentstack_network_external_device }} -j MASQUERADE
      when: ipt_masquerade|failed
