---
- hosts: all
  sudo: True
  tasks:
    - name: disable grid5000 http_proxy by default
      lineinfile:
        dest: /etc/environment
        regexp: '^http_proxy="http://proxy:3128"'
        state: absent
