---
- hosts: all
  sudo: True
  roles:
    - upgrade
    - chrony

- hosts: controller
  sudo: True
  tasks:

    - name: ensure required packages for prep are installed
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - python-mysqldb
        - python-keystoneclient

- hosts: all:!network
  sudo: True
  tasks:

    - name: update static route configuration script
      copy:
        dest: /etc/network/if-up.d/openstack-demo-static-route
        owner: root
        group: root
        mode: 0755
        content: "#!/bin/sh\nroute add -net 10.2.0.0/16 gw 10.1.0.3\n"
      register: static_route_script

    - name: ensure that static route script is run at least once
      command: /etc/network/if-up.d/openstack-demo-static-route
      when: static_route_script|changed 
      failed_when: false
